apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-green-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-green
  template:
    metadata:
      labels:
        app: kube-green
    spec:
      containers:
        - name: operator
          image: docker.io/karimullah1303/green-kube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080