apiVersion: v1
kind: Service
metadata:
  name: green-kube-service
  namespace: default
spec:
  selector:
    app: green-kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
